edu/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login,logout

app_name='edu'

urlpatterns = [
    url(r'^$', views.index),
    url(r'^login/$',login,{'template_name': 'edu/login.html'}),
    url(r'^logout/$',logout,{'template_name': 'edu/logout.html'}),
    url(r'^register/$',views.register,name='register'),
    url(r'^student/$',views.StudentView.as_view(),name='student_details'),
    url(r'^student/entry/$',views.StudentEntry.as_view(),name='student-entry'),
    url(r'^student/(?P<pk>[0-9]+)/$',views.StudentUpdate.as_view(),name='student-update'),
    url(r'^student/(?P<pk>[0-9]+)/delete$',views.StudentDelete.as_view(),name='student-delete'),




]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from mysite import views

urlpatterns = [
    url(r'^$',views.login_redirect,name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('edu.urls')),


]

edu/models.py
from django.db import models
from django.urls import reverse

class Profile(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email=models.EmailField(max_length=50)
    birth_date = models.DateTimeField()

class Student(models.Model):

    stu_name=models.CharField(max_length=100)
    stu_email=models.EmailField(max_length=50)
    stu_phone_no=models.CharField(max_length=40)
    stu_dob=models.DateField()

    def get_absolute_url(self):
        return reverse('edu:student_details')

edu/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm

class RegistrationForm(UserCreationForm):
    email=forms.EmailField(required=True)
    phone_no=forms.CharField(required=True)

    class Meta:
        model=User
        fields={
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'phone_no',
             }
        field_order=['username','first_name','last_name','email','password1','password2','phone_no']

    def save(self,commit=True):
            user=super(RegistrationForm,self).save(commit=false)
            user.first_name=cleaned_data['first_name']
            user.last_name=cleaned_data['last_name']
            user.email=cleaned_data['email']

            if commit:
                user.save()

            return user

edu/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView
from edu.forms import RegistrationForm
from edu.models import Student
from django.views import generic
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.urls import reverse_lazy,reverse


# Create your views here.
def index(request):
    name='khyati'
    args={'name':name}

    return render(request,'edu/index.html',args)

def register(request):
    if request.method=='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/account')
    else:
        form=RegistrationForm()
        args={'form':form}
        return render(request,'edu/reg_form.html',args)

class StudentView(generic.ListView):
    context_object_name='student_list'
    template_name='edu/student_details.html'

    def get_queryset(self):
        return Student.objects.all()

class StudentEntry(CreateView):
    model=Student
    fields=['stu_name','stu_email','stu_phone_no','stu_dob']

class StudentUpdate(UpdateView):
    model=Student
    fields=['stu_name','stu_email','stu_phone_no','stu_dob']

class StudentDelete(DeleteView):
    model=Student
    success_url=reverse_lazy('edu:student_details')

mysite/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('account/login')

edu/templates/base.html
<!DOCTYPE html>
<html>
    <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        {% block title %}
        <meta charset="utf-8">
        <title>Howdy!</title>
        {% endblock %}
    </head>
    <body>

        <div>
            <a href="/account/register">register</a>
        </div>

        {% block body %}


            <form method="post">
                First Name<input type="text" value="{{ Profile.first_name }}">
                Last Name<input type="text">
                Email:<input type="email",name="email">
                Password<input type ="password",name="password">
                DOB<input type="date">
              <button type="submit">Login</button>
            </form>
        {% endblock %}
    </body>
</html>

edu/templates/edu/index.html
<!-- howdy/templates/index.html -->

{% extends 'base.html' %}

{% block title %}
    <title>home</title>
{% endblock %}

{% block body %}
    hello
    {{name}}
{% endblock %}

edu/templates/edu/login.html
{% extends 'base.html' %}
    {% block title %}
        <meta charset="UTF-8">
        <title>Title</title>
    {% endblock %}

    {% block body %}

        <h1>you can logged in</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="login" name="register">
        </form>

    {% endblock %}

edu/templates/edu/logout.html
{% extends 'base.html' %}
    {% block title %}
        <meta charset="UTF-8">
        <title>Title</title>
    {% endblock %}

    {% block body %}
        <h1>you have successfully logged off</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="login" name="register">
            </form>
    {% endblock %}

edu/templates/edu/reg_form.html
{% extends 'base.html' %}
    {% block title %}
    <meta charset="UTF-8">
    <title>Title</title>
    {% endblock %}

    {% block body %}

            <form method="POST">
            <div class="container">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="register" name="register">
            </form>
        </div>

    {% endblock %}

edu/templates/edu/student_details.html
{%  extends 'base.html' %}
{% block body %}
    {%  if student_list %}

        {% for student in student_list %}
            <ul>
            <li>
                <h2>Name:{{student.stu_name}}</h2>
                <h2>Email:{{student.stu_email}}</h2>
                <h2>Phone No.:{{student.stu_phone_no}}</h2>
                <h2>Date Of Birth:{{student.stu_dob}}</h2>

                    <form action="{% url 'edu:student-delete' student.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-sm">Delete</button>
                    </form>
                    <form action="{% url 'edu:student-update' student.id  %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default btn-sm">Update</button>
                    </form>


            </li>
            </ul>
        {% endfor %}
    {% else %}
        <h1>No student entries found on the databse</h1>
    {% endif %}

    <form action="{% url  'edu:student-entry' %}" method="post" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-default btn-sm">Make a student entry here</button>
    </form>
{% endblock %}

edu/templates/edu/student_form.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        Add a New Student
    </div>

    <div class="container">
        {%  if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}

    <form action="" method="POST" enctype="multipart/form-data">
        {%  csrf_token  %}
        {% include 'edu/form-template' %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success" name="register">Submit</button>
            </div>
        </div>
    </form>
    </div>
{% endblock %}